#! /usr/bin/env bash

apt-get update > /dev/null

apt-get install --yes --force-yes ruby ri bundler

su - vagrant -c "cd /vagrant ; mkdir -p ~/vendor/bundle vendor ; ln -sf ~/vendor/bundle vendor/bundle"
su - vagrant -c "cd /vagrant ; bundle install --path vendor/bundle"

